export const DISPLAY_TODOS = 'DISPLAY_TODOS';
export const ADD_TODO = 'ADD_TODO';
export const SELECT_ITEM_TO_UPDATE = 'SELECT_ITEM_TO_UPDATE';
export const UPDATE_TODO = 'UPDATE_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const REMOVE_COMPLETED_TODOS = 'REMOVE_COMPLETED_TODOS';
export const TOGGLE_TODO_STATUS = 'TOGGLE_TODO_STATUS';
export const TOGGLE_EVERY_TODO_STATUS = 'TOGGLE_EVERY_TODO_STATUS';
